default: &default
  adapter: postgresql
  host: localhost
  username: postgres
  password: postgres  
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  # database: demo_registration_app_development
  database: demo_registration_new_development
  